force-app/main/default/objects/WebServiceSetting__mdt/WebServiceSetting__mdt.object-meta.xml
<CustomObject>
    <label>WebServiceSetting</label>
    <pluralLabel>WebServiceSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/WebServiceSetting__mdt/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WebServiceSetting__mdt/fields/Retry_Interval_Mins__c.field-meta.xml
<CustomField>
    <fullName>Retry_Interval_Mins__c</fullName>
    <defaultValue>15</defaultValue>
    <label>Retry Interval Mins</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WebServiceSetting__mdt/fields/URI__c.field-meta.xml
<CustomField>
    <fullName>URI__c</fullName>
    <label>URI</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WebServiceSetting__mdt/fields/Verb__c.field-meta.xml
<CustomField>
    <fullName>Verb__c</fullName>
    <label>Verb</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VirtualWebService.cls
/* @author: michael murphy
 * @date: <2019-08-19>
 * @description: this is where methods which may be overriden live for ws.  All ws should extend me
 * @history: <2019-08-19>: michael murphy: Created
 * */

public virtual class VirtualWebService {
    protected WebServiceSetting__mdt wsSetting;
    protected String thisClassName;


    public VirtualWebService() {
        this.thisClassName = String.valueOf(this).split(':')[0];
        this.wsSetting = getWsSettings(this.thisClassName);
    }

    protected WebServiceSetting__mdt getWsSettings(String wsName) {
        return [SELECT id
                , developername
                , retry__c
                , retry_interval_mins__c
                , uri__c
                , verb__c
                , body__c
                FROM WebServiceSetting__mdt
                WHERE developername = :wsName];
    }

    protected virtual void error() {
        throw new VirtualWebServiceException();
    }


    protected virtual void retry() {
        if(!wsSetting.retry__c)
            { return; }
        
        Type t;

        try {
            t = Type.forName(String.valueOf(this).split(':')[0]);
        } catch (Exception e) {
            System.debug(e.getMessage());
            error();
        }
        
        System.schedule(thisClassName + String.valueOf(DateTime.now())
                        , '0 ' + String.valueOf(wsSetting.Retry_Interval_Mins__c) + ' * * * ?'
                        , new WebServiceScheduler((System.Queueable)t.newInstance()));
    }

    protected virtual HttpResponse callout() {
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse(); 

        req.setEndpoint(this.wsSetting.uri__c);
        req.setMethod(this.wsSetting.verb__c);
        res = h.send(req);

        if(!String.valueOf(res.getStatusCode()).startsWith('2'))
            { retry(); }

        return res;
    }

    public class VirtualWebServiceException extends Exception {}
}